### ISSUE TITLE
Few suggestions and possible bugs.

### ISSUE THREAD

**Issue by dragonCASTjosh** [volcoma/EtherealEngine#2]
## Overview
So i have been playing with the engine and editor for a few days now and i have stumbled upon a few things missing or not working

## Materials Editor
There is no materials from within the editor. Personally, i feel this is a very important feature for any engine to have as without such a feature it becomes difficult and tedious to create a level for your game. I recommend doing this through a selection of default shaders that the user can choose from and then it open up properties and textures inputs based upon the shader.

## Drag and Drop
From what i could tell there is no way to drag models or other assets from the asset browser into the current scene and if there is then it is not working correctly. This feature should not only work for dragging into the scene but also for dragging assets into the inspector. **Correction, i have re-read the Reedme and found you need to use middle mouse, this is not natural for many users and impossible on laptops.**

## Statistic Dropdown issues
I have had a small issue where the statistics dropdown box is difficult to click, i end up spamming click until it hit the small zone that causes it to open, this is something that could do with fixing.

## BGFX Issues
When trying to run DX12 and Vulkan i came across a few issues in the form of DX12 crashing upon startup and Vulkan reverting back to DX11. I am on windows 10 and my GPU is a 970 on the newest drivers. I believe these issues would be solved by updating bgfx to the newest version. 

## Documentation
When trying to learn and understand the engine i couldn't help but feel there was a strong need for proper hand written documentation, this would help people learn and understand the engine much faster and would also make the engine more accessable. I recommend you do this sooner rather than later so you can do it slowly over time rather than all the docs within a month with no new features.

**Comment by volcoma** [comment]
Well man really thanks for the feedback. The engine is still in super early stages and therer are a lot of issues to be fixed. In regards to your feedback:
Materials: Currently materials can be created from the editor by right clicking on the content region of the assets tab and clicking on the "Create Material" item of the context menu like so:
![guide1](https://cloud.githubusercontent.com/assets/1499411/21582083/fb8cd6f4-d052-11e6-91c2-7c1248eb1f94.png)

then you can select the material and edit its properties via the inspector like so:
![guide2](https://cloud.githubusercontent.com/assets/1499411/21582173/171aa970-d056-11e6-839d-b611a13cc6e3.png)

Currently its only the Standard Material you can create which will be used later with the pbr rendering when i get to it. After that you can drag and drop the material on some material slot in the for example model component. Yes you can drag the assets from the asset browser to a link space(for example a texture slot of a material) or into the hierarchy tab(for models and prefabs). Currently you can't drag them onto the scene tab(I will make that happen at some point). I will also try to fix the dragging to be with the left mouse button. You can select all the assets in the assets browser and they should appear in the inspector.You can also drag an entity or a whole entity hierarchy from the hierarchy tab to the assets browser/prefabs and it should save it as a prefab which you can use later(it is a working version but i have some more work on that. Right clicking on an entity also gives you a context menu with options.

I've recently finished with a feature allowing you to modify a shader's code and just saving the raw shader file and the editor should automatically detect the changes and compile it on and apply it without having to manually compile them. The plan is to do that for all assets and that will be my next step.

About the statistics dropdown. I was waiting for the bgfx library guy to expose some more stats and then i was gonna change that dropdown a bit. Currently it's there mainly for my benefit when im testing stuff...

As for the vulkan and dx12 support. I am not sure if bgfx supports that fully yet. I know there is work done on it but i have to check if its complete. If so i should upgrade the shader compiling to also include vulkan stuff.

Well you are right about the documentation. The issue here is time for me as I am working on the engine in my free time since i got a job and stuff and the time that i get to spend developing it i really wouldn't like to spend on the paper work of it, also i wasn't expecting somoene to look into the engine so early and to actually wanna play around with it but i guess github makes wonders happen. :)

I appreciate the feedback so much! If you have any questions or more feedback(positive or negative) especially the second, don't hessitate to share it with me :+1:

**Comment by volcoma** [comment]
Thanks, you are the man :+1: . I have some experience with rendering as well. If you want to bounce ideas or smth like that, i am here here :+1: . I have a lot of rendering code from my previous engine  https://www.youtube.com/watch?v=5ikjLSok-84&t

that i can also transfer into this one. Also Happy New Year !

**Comment by dragonCASTjosh** [comment]
Funny thing is i have seen them videos in the past and really wanted to look through the source of that engine because the results were awesome. 

Happy New Year.

**Comment by volcoma** [comment]
Well i guess i fixed the dragging and dropping to work with left mouse button.

**Comment by dragonCASTjosh** [comment]
Awesome

**Comment by dragonCASTjosh** [comment]
I would also recommend updating the projects tab as it only seems to have stuff for the editor. It may give me something to look into working on :)

**Comment by volcoma** [comment]
do you mean i should define some more smaller tasks or features? btw i just finished some drag and drop stuff that allows you to drop meshes and prefabs into the scene directly and it should project the position onto the xz plane

**Comment by dragonCASTjosh** [comment]
i mean you have the projects tab but most sections are empty, if you fill them in with features you would like to see in them areas people like me could help out. And i noticed when i pulled the newest version this morning, it makes it so much easier to use.

**Comment by volcoma** [comment]
I've updated the projects tab with some tasks and features. I will try to keep it updated. If you have any suggestions for features or something for example that you would like working on i am open for it

**Comment by dragonCASTjosh** [comment]
i think that is a good list of features to start with. I will look into learning the engine so i can help with some of the features

**Comment by dragonCASTjosh** [comment]
if you add in the basic lighting whilst i learn the engine work on the PBR go from there

**Comment by ArnCarveris** [comment]
Please make PBR as optional.

**Comment by dragonCASTjosh** [comment]
What do you lose using PBR, you only really gain a workflow making it easier to get high quality results

**Comment by ArnCarveris** [comment]
runtime performance

**Comment by dragonCASTjosh** [comment]
Should be less then 1ms per scene so not noticeable

**Comment by dragonCASTjosh** [comment]
The stats are from my Urho3D implementation, running on a friends 650ti. The important parts of what I used was lambert diffuse, ggx distribution and epics mobile approximation for the IBL. Running on the sponza scene. If I implement it here I'd likely allow users choose each model in use similar to what xenko is doing

**Comment by dragonCASTjosh** [comment]
@volcoma i never did ask why you stopped with insomnium engine

**Comment by volcoma** [comment]
well there was a lot of legacy code, most of it was c++ 98 style, there were a lot of architectural decisions which were not great and i made a lot of mistakes there. Didn't have an editor and setupping stuff was super painful. Was only dx11 and not really cross platform oriented and much more. :).  We learn from our mistakes. It helped me learn a lot and i think i can do a way better job with this one :)

**Comment by dragonCASTjosh** [comment]
id love to play around with as the results were extremely nice. and i imagine the source is a lot more readable the unreal :D

**Comment by ArnCarveris** [comment]
Would be nice if such system(http://www.sectr.co/core.html) will be build-in.

**Comment by christianclavet** [comment]
Hi, Just tried it and compiled without any problem on windows. I was assuming I would have to download a lot of dependency, but once I downloaded the repo, it compiled and worked directly!

Everything I see now is really well done for a WIP engine! I will be very happy if you can add hardware skinning and animations blending. This is working 100% (Gui a little small but ok) on my 4k screen here! 

Tried the editor and was able to load a model, create lights, create a material and assign it a texture. For a start of a editor this is quite a feat! The rendering is quite nice too! Congrat!
![screenshot](https://cloud.githubusercontent.com/assets/13395943/24734465/89f68100-1a4b-11e7-829d-1cbca11a9d38.jpg)
